service: S3toEC2Copy

frameworkVersion: '2'

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  bucketName: myserverlessdemobucket-1456447894516578941264712

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: playground
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'
  environment:
    bucketName: ${self:custom.bucketName}

functions:
  gets3Object:
    handler: lambdas/endpoints/getS3Object.handler
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
          # uncomment if bucket is not managed by serverless
          #existing: true