# MANUAL STEPS
# lambda needs IAM access to the ssm.sendmessage on the ec2 instance in question
# ensure aws CLI & SSM are installed on the destination and added to the PATH e.g. you can run aws --version from powershell

service: S3toEC2Copy

frameworkVersion: '2'

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  # Ensure to set this to a non real bucket before checking the code back into the repo as the repo is public
  bucketName: myserverlessdemobucket123

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: playground
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'
  environment:
    bucketName: ${self:custom.bucketName}

functions:
  gets3Object:
    handler: lambdas/getS3Object.handler
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
          # uncomment if bucket is not managed by serverless e.g. the bucket was manually created
          #existing: true
