service: simplelambdaandapigateway

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: playground
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get