service: SimpleAPIKeys

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: playground
  region: eu-west-1
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'
  apiKeys:
    - free:
      - myFreeApiKey
    - paid:
      - myPaidApiKey
  usagePlan:
      - free:
          quota:
              limit: 1000
              period: MONTH
          throttle:
              rateLimit: 5
              burstLimit: 20
      - paid:
          quota:
              limit: 10000
              period: MONTH
          throttle:
              burstLimit: 20
              rateLimit: 5

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  tableName: player-points

resources:
  Resources:
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  getPlayerScore:
    handler: lambdas/endpoints/getPlayerScore.handler
    events:
      - http:
          path: get-player-score/{ID}
          method: GET
          cors: true
          private: true
  createPlayerScore:
    handler: lambdas/endpoints/createPlayerScore.handler
    events:
      - http:
          path: create-player-score/{ID}
          method: POST
          cors: true
          private: true