service: DynamoDbAndAPIGateway

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: playground
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:*
      Resource: '*'
  
plugins:
  - serverless-webpack

package:
  individually: true

functions:
  sendEmail:
    handler: lambdas/endpoints/sendEmail.handler
    events:
      - http:
          path: send-email
          method: POST
          cors: true